/**
 * Render GSD requirements as a markdown table for REQUIREMENTS.md.
 */

import type { RequirementRow } from "../db/types.js";

/**
 * Produce a markdown table of all requirements.
 *
 * Columns: ID | Class | Description | Status | Source
 */
export function renderRequirementsMarkdown(
  requirements: RequirementRow[],
): string {
  const header = `<!-- Auto-generated by /gsd import. Do not edit manually. -->`;
  const tableHeader = `| ID | Class | Description | Status | Source |`;
  const tableSeparator = `|---|---|---|---|---|`;

  if (requirements.length === 0) {
    return `${header}\n\nNo requirements imported yet.\n`;
  }

  const rows = requirements.map((r) => {
    const desc = r.description.length > 80
      ? r.description.slice(0, 77) + "..."
      : r.description;
    return `| ${r.id} | ${r.class} | ${desc} | ${r.status} | ${r.source} |`;
  });

  return [header, "", tableHeader, tableSeparator, ...rows, ""].join("\n");
}
